#!/usr/bin/env bash

# Add all Reddit subscriptions
# Using top posts from the week to reduce noise

subreddits=(
  "10s"
  "35mm"
  "50mm"
  "amateurradio"
  "AnalogRepair"
  "Anki"
  "Anthropic"
  "Anticonsumption"
  "ArtificialIntelligence"
  "AverageBattlestations"
  "BackyardOrchard"
  "Beekeeping"
  "BeginnerWoodWorking"
  "Bogleheads"
  "BootstrappedStartups"
  "Breadit"
  "BudgetAudiophile"
  "buildingpublic"
  "BuyItForLife"
  "Calisthenic"
  "Cameras"
  "CargoBike"
  "ChatGPT"
  "ChatGPTCoding"
  "CityBuilders"
  "ClaudeAI"
  "ClaudeCode"
  "clevercomebacks"
  "CLI"
  "commonplacebook"
  "Costco"
  "Deals_Pricely"
  "diySolar"
  "EatCheapAndHealthy"
  "EntrepreneurRideAlong"
  "esp32"
  "Exercise"
  "ExperiencedDevs"
  "expo"
  "FenceBuilding"
  "Fjallraven"
  "flipclocks"
  "Frugal"
  "frugalmalefashion"
  "FuckYourEamesLounge"
  "furniture"
  "gaggiaclassic"
  "gardening"
  "GetMotivated"
  "Ghostty"
  "GreatestPhotos"
  "Greenhouses"
  "HeritageWear"
  "hobiekayaks"
  "homeassistant"
  "homelab"
  "Homesteading"
  "HowToAIAgent"
  "HTBuyingGuides"
  "HumansBeingBros"
  "Hydroponics"
  "IkeaGreenhouse"
  "immich"
  "indiehackers"
  "intermittentfasting"
  "iosapps"
  "JamesHoffmann"
  "JellyfinCommunity"
  "Journaling"
  "jumprope"
  "kayakfishing"
  "landscaping"
  "learn_tech"
  "leetcode"
  "LifeProTips"
  "linux_on_mac"
  "M43"
  "macgaming"
  "macsetups"
  "MadeMeSmile"
  "micro_saas"
  "microsaas"
  "midcenturymodern"
  "minilab"
  "MobileAppDevelopment"
  "Montero"
  "MyFreelancetoAgency"
  "myog"
  "NoCodeSaaS"
  "NoLawns"
  "onebag"
  "OpenAI"
  "opendirectories"
  "opensource"
  "OutOfTheLoop"
  "overlanding"
  "passive_income"
  "photogrammetry"
  "Piracy"
  "prettyusefulwebsites"
  "PurchaseWithPurpose"
  "QuantifiedSelf"
  "reactnative"
  "robotics"
  "roguelikedev"
  "rust"
  "SaaS"
  "selfhosted"
  "seriouseats"
  "SewingForBeginners"
  "SideProject"
  "singlespeedcycling"
  "SolarDIY"
  "SoloDevelopment"
  "startups"
  "streetphotography"
  "SurfFishing"
  "tapeless"
  "TheFounders"
  "ThriftStoreHauls"
  "tmux"
  "tomsachs"
  "toptalent"
  "ToyotaSienna"
  "tradewithcongress"
  "travelblog"
  "tui"
  "VibeCodersNest"
  "vibecoding"
  "videos"
  "vintageart"
  "VintageDigitalCameras"
  "Visiblemending"
  "Volvo240"
  "wallpaper"
  "web_design"
  "Whatcouldgowrong"
  "Workbenches"
  "Workspaces"
  "zlibrary"
)

echo "Adding ${#subreddits[@]} Reddit feeds..."
echo ""

added=0
skipped=0
failed=0

for sub in "${subreddits[@]}"; do
  echo "Processing r/$sub..."

  if ./rss add "https://www.reddit.com/r/$sub" 2>&1 | grep -q "already exists"; then
    echo "  ⚠️  Already exists, skipping"
    ((skipped++))
  elif ./rss add "https://www.reddit.com/r/$sub" 2>&1 | grep -q "Added feed"; then
    echo "  ✅ Added successfully"
    ((added++))
  else
    echo "  ❌ Failed to add"
    ((failed++))
  fi

  echo ""
done

echo "======================================"
echo "Summary:"
echo "  Added: $added"
echo "  Skipped (already exist): $skipped"
echo "  Failed: $failed"
echo "======================================"
